apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  clusterIP: "None"
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql
    app: demo
    role: mysqldb
